-- Create Wallets Table (Banks)
create table if not exists public.wallets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, name)
);

-- Enable RLS for Wallets
alter table public.wallets enable row level security;

create policy "Users can view their own wallets"
on public.wallets for select
using (auth.uid() = user_id);

create policy "Users can insert their own wallets"
on public.wallets for insert
with check (auth.uid() = user_id);

create policy "Users can update their own wallets"
on public.wallets for update
using (auth.uid() = user_id);

create policy "Users can delete their own wallets"
on public.wallets for delete
using (auth.uid() = user_id);

-- Create Debts Table (Liabilities)
create table if not exists public.debts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  total_amount numeric default 0,
  remaining_amount numeric default 0,
  due_date date,
  notes text,
  is_paid boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Debts
alter table public.debts enable row level security;

create policy "Users can view their own debts"
on public.debts for select
using (auth.uid() = user_id);

create policy "Users can insert their own debts"
on public.debts for insert
with check (auth.uid() = user_id);

create policy "Users can update their own debts"
on public.debts for update
using (auth.uid() = user_id);

create policy "Users can delete their own debts"
on public.debts for delete
using (auth.uid() = user_id);

-- Add wallet_id to transactions if not exists
do $$
begin
    if not exists (select 1 from information_schema.columns where table_name = 'transactions' and column_name = 'wallet_id') then
        alter table public.transactions add column wallet_id bigint references public.wallets(id) on delete set null;
    end if;
end $$;
