-- ============================================================================
-- COMPLETE DATABASE SCHEMA V2 - OPTIMIZED & EFFICIENT
-- Clean slate approach - Best practices implementation
-- ============================================================================

-- Drop all existing tables to start fresh
DROP VIEW IF EXISTS public.project_spending_summary CASCADE;
DROP VIEW IF EXISTS public.wallet_balances CASCADE;

DROP TABLE IF EXISTS public.asset_transactions CASCADE;
DROP TABLE IF EXISTS public.budget_alerts CASCADE;
DROP TABLE IF EXISTS public.transaction_tag_assignments CASCADE;
DROP TABLE IF EXISTS public.transaction_tags CASCADE;
DROP TABLE IF EXISTS public.financial_goals CASCADE;
DROP TABLE IF EXISTS public.recurring_transactions CASCADE;
DROP TABLE IF EXISTS public.tasks CASCADE;
DROP TABLE IF EXISTS public.task_categories CASCADE;
DROP TABLE IF EXISTS public.transactions CASCADE;
DROP TABLE IF EXISTS public.transaction_items CASCADE;
DROP TABLE IF EXISTS public.budgets CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.assets CASCADE;
DROP TABLE IF EXISTS public.projects CASCADE;
DROP TABLE IF EXISTS public.debts CASCADE;
DROP TABLE IF EXISTS public.wallets CASCADE;

-- Drop existing enums
DROP TYPE IF EXISTS project_status CASCADE;
DROP TYPE IF EXISTS task_status CASCADE;
DROP TYPE IF EXISTS task_priority CASCADE;
DROP TYPE IF EXISTS transaction_type CASCADE;
DROP TYPE IF EXISTS asset_type CASCADE;
DROP TYPE IF EXISTS category_type CASCADE;
DROP TYPE IF EXISTS frequency_type CASCADE;
DROP TYPE IF EXISTS alert_type CASCADE;

-- ============================================================================
-- ENUMS - Standardized across application
-- ============================================================================

CREATE TYPE transaction_type AS ENUM ('income', 'expense', 'transfer');
CREATE TYPE category_type AS ENUM ('income', 'expense');
CREATE TYPE project_status AS ENUM ('planning', 'in_progress', 'completed', 'on_hold', 'cancelled');
CREATE TYPE task_status AS ENUM ('todo', 'done');
CREATE TYPE task_priority AS ENUM ('urgent', 'high', 'medium', 'low');
CREATE TYPE asset_type AS ENUM ('stock', 'crypto', 'bond', 'mutual_fund', 'real_estate', 'other');
CREATE TYPE frequency_type AS ENUM ('daily', 'weekly', 'monthly', 'quarterly', 'yearly');
CREATE TYPE alert_type AS ENUM ('warning', 'exceeded', 'approaching');

-- ============================================================================
-- CORE TABLES
-- ============================================================================

-- ============================================================================
-- 1. CATEGORIES
-- Purpose: Income/Expense categorization
-- ============================================================================
CREATE TABLE public.categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  name text NOT NULL,
  type category_type NOT NULL,
  icon text, -- Icon name for UI
  color text, -- Hex color code
  is_system boolean DEFAULT false, -- System categories can't be deleted
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE(user_id, name, type)
);

CREATE INDEX idx_categories_user_type ON public.categories(user_id, type);

-- ============================================================================
-- 2. TRANSACTION ITEMS (Master data for transactions)
-- Purpose: Template/master data for common transactions
-- ============================================================================
CREATE TABLE public.transaction_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  category_id bigint REFERENCES public.categories ON DELETE SET NULL,
  name text NOT NULL,
  code text NOT NULL,
  default_amount numeric, -- Suggested amount
  is_favorite boolean DEFAULT false, -- Quick access
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE(user_id, code)
);

CREATE INDEX idx_transaction_items_user_category ON public.transaction_items(user_id, category_id);
CREATE INDEX idx_transaction_items_favorite ON public.transaction_items(user_id, is_favorite) WHERE is_favorite = true;

-- ============================================================================
-- 3. WALLETS (Bank accounts, e-wallets, cash, credit cards)
-- Purpose: Money containers
-- ============================================================================
CREATE TABLE public.wallets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  name text NOT NULL,
  type text NOT NULL, -- 'bank', 'cash', 'credit_card', 'e_wallet', 'investment'
  initial_balance numeric DEFAULT 0 NOT NULL,
  current_balance numeric DEFAULT 0 NOT NULL, -- Cached for performance
  currency text DEFAULT 'IDR' NOT NULL,
  icon text,
  color text,
  is_active boolean DEFAULT true NOT NULL,
  is_excluded_from_total boolean DEFAULT false, -- Exclude from net worth (e.g., credit cards)
  account_number text, -- Masked: **** 1234
  notes text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE(user_id, name)
);

CREATE INDEX idx_wallets_user_active ON public.wallets(user_id, is_active);
CREATE INDEX idx_wallets_type ON public.wallets(user_id, type);

-- ============================================================================
-- 4. PROJECTS
-- Purpose: Budget tracking for specific initiatives
-- ============================================================================
CREATE TABLE public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  name text NOT NULL,
  description text,
  total_budget numeric DEFAULT 0 NOT NULL,
  spent_amount numeric DEFAULT 0 NOT NULL, -- Cached, recalculated from transactions
  status project_status DEFAULT 'planning' NOT NULL,
  start_date date,
  deadline date,
  completion_date date,
  priority integer DEFAULT 0, -- For sorting
  color text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE(user_id, name)
);

CREATE INDEX idx_projects_user_status ON public.projects(user_id, status);
CREATE INDEX idx_projects_deadline ON public.projects(user_id, deadline) WHERE status IN ('planning', 'in_progress');

-- ============================================================================
-- 5. DEBTS / LIABILITIES
-- Purpose: Track loans, credit, liabilities
-- ============================================================================
CREATE TABLE public.debts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  name text NOT NULL,
  creditor text, -- Bank name, person name, etc.
  total_amount numeric NOT NULL,
  remaining_amount numeric NOT NULL,
  monthly_payment numeric DEFAULT 0,
  interest_rate numeric DEFAULT 0, -- Annual percentage
  start_date date,
  due_date date,
  is_paid boolean DEFAULT false NOT NULL,
  notes text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX idx_debts_user_status ON public.debts(user_id, is_paid);
CREATE INDEX idx_debts_due_date ON public.debts(user_id, due_date) WHERE is_paid = false;

-- ============================================================================
-- 6. TRANSACTIONS (The heart of the system)
-- Purpose: All money movements
-- ============================================================================
CREATE TABLE public.transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,

  -- Core transaction data
  type transaction_type NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0),
  date date NOT NULL DEFAULT CURRENT_DATE,
  description text NOT NULL,
  notes text,

  -- References
  wallet_id bigint REFERENCES public.wallets ON DELETE SET NULL,
  to_wallet_id bigint REFERENCES public.wallets ON DELETE SET NULL, -- For transfers
  item_id bigint REFERENCES public.transaction_items ON DELETE SET NULL,
  project_id bigint REFERENCES public.projects ON DELETE SET NULL,
  debt_id bigint REFERENCES public.debts ON DELETE SET NULL,

  -- Metadata
  is_recurring boolean DEFAULT false, -- Generated from recurring template
  recurring_transaction_id bigint, -- FK added later
  receipt_url text, -- Photo/document storage
  location text, -- GPS or manual entry

  -- Audit
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,

  -- Constraints
  CHECK (
    (type = 'transfer' AND to_wallet_id IS NOT NULL) OR
    (type IN ('income', 'expense') AND to_wallet_id IS NULL)
  )
);

CREATE INDEX idx_transactions_user_date ON public.transactions(user_id, date DESC);
CREATE INDEX idx_transactions_wallet ON public.transactions(wallet_id);
CREATE INDEX idx_transactions_project ON public.transactions(project_id) WHERE project_id IS NOT NULL;
CREATE INDEX idx_transactions_debt ON public.transactions(debt_id) WHERE debt_id IS NOT NULL;
CREATE INDEX idx_transactions_type ON public.transactions(user_id, type);
CREATE INDEX idx_transactions_date_range ON public.transactions(user_id, date);

-- ============================================================================
-- 7. TRANSACTION TAGS (Flexible categorization)
-- Purpose: Multi-dimensional tagging beyond categories
-- ============================================================================
CREATE TABLE public.transaction_tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  name text NOT NULL,
  color text,
  icon text,
  created_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE(user_id, name)
);

CREATE INDEX idx_transaction_tags_user ON public.transaction_tags(user_id);

-- Junction table for many-to-many
CREATE TABLE public.transaction_tag_assignments (
  transaction_id bigint REFERENCES public.transactions ON DELETE CASCADE NOT NULL,
  tag_id bigint REFERENCES public.transaction_tags ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (transaction_id, tag_id)
);

CREATE INDEX idx_tag_assignments_transaction ON public.transaction_tag_assignments(transaction_id);
CREATE INDEX idx_tag_assignments_tag ON public.transaction_tag_assignments(tag_id);

-- ============================================================================
-- 8. BUDGETS (Monthly/Periodic budget planning)
-- Purpose: Set spending limits per category
-- ============================================================================
CREATE TABLE public.budgets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  category_id bigint REFERENCES public.categories ON DELETE CASCADE,
  amount numeric NOT NULL CHECK (amount >= 0),
  spent_amount numeric DEFAULT 0 NOT NULL, -- Cached
  month integer NOT NULL CHECK (month BETWEEN 1 AND 12),
  year integer NOT NULL CHECK (year >= 2000),
  notes text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE(user_id, category_id, month, year)
);

CREATE INDEX idx_budgets_user_period ON public.budgets(user_id, year, month);
CREATE INDEX idx_budgets_category ON public.budgets(category_id);

-- ============================================================================
-- 9. BUDGET ALERTS
-- Purpose: Automated warnings when budget limits approached/exceeded
-- ============================================================================
CREATE TABLE public.budget_alerts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  budget_id bigint REFERENCES public.budgets ON DELETE CASCADE NOT NULL,
  alert_type alert_type NOT NULL,
  threshold_percentage numeric DEFAULT 80 CHECK (threshold_percentage BETWEEN 0 AND 100),
  is_active boolean DEFAULT true NOT NULL,
  last_triggered_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX idx_budget_alerts_budget ON public.budget_alerts(budget_id, is_active);

-- ============================================================================
-- 10. RECURRING TRANSACTIONS
-- Purpose: Templates for automatic transaction generation
-- ============================================================================
CREATE TABLE public.recurring_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,

  -- Transaction template
  type transaction_type NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0),
  description text NOT NULL,
  notes text,

  -- References (same as transactions)
  wallet_id bigint REFERENCES public.wallets ON DELETE CASCADE,
  to_wallet_id bigint REFERENCES public.wallets ON DELETE SET NULL,
  item_id bigint REFERENCES public.transaction_items ON DELETE SET NULL,
  project_id bigint REFERENCES public.projects ON DELETE SET NULL,

  -- Recurrence settings
  frequency frequency_type NOT NULL,
  start_date date NOT NULL,
  end_date date, -- NULL = indefinite
  next_occurrence date NOT NULL,
  last_generated_date date,

  -- Status
  is_active boolean DEFAULT true NOT NULL,
  auto_generate boolean DEFAULT true, -- Auto-create or just remind

  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- Add FK to transactions
ALTER TABLE public.transactions
  ADD CONSTRAINT fk_recurring_transaction
  FOREIGN KEY (recurring_transaction_id)
  REFERENCES public.recurring_transactions(id)
  ON DELETE SET NULL;

CREATE INDEX idx_recurring_user_active ON public.recurring_transactions(user_id, is_active);
CREATE INDEX idx_recurring_next_occurrence ON public.recurring_transactions(next_occurrence) WHERE is_active = true;

-- ============================================================================
-- 11. FINANCIAL GOALS
-- Purpose: Savings targets and financial objectives
-- ============================================================================
CREATE TABLE public.financial_goals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  name text NOT NULL,
  description text,
  target_amount numeric NOT NULL CHECK (target_amount > 0),
  current_amount numeric DEFAULT 0 NOT NULL CHECK (current_amount >= 0),
  category text, -- 'emergency_fund', 'house', 'car', 'vacation', 'retirement', etc.
  deadline date,
  is_achieved boolean DEFAULT false NOT NULL,
  achieved_at timestamptz,
  priority integer DEFAULT 0,
  icon text,
  color text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX idx_financial_goals_user_status ON public.financial_goals(user_id, is_achieved);
CREATE INDEX idx_financial_goals_deadline ON public.financial_goals(user_id, deadline) WHERE is_achieved = false;

-- ============================================================================
-- 12. ASSETS / INVESTMENTS
-- Purpose: Track investment portfolio
-- ============================================================================
CREATE TABLE public.assets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,

  -- Asset identification
  type asset_type NOT NULL,
  symbol text NOT NULL, -- Ticker symbol or unique identifier
  name text, -- Full name

  -- Holdings
  quantity numeric NOT NULL CHECK (quantity > 0),
  avg_buy_price numeric NOT NULL CHECK (avg_buy_price > 0),
  current_price numeric DEFAULT 0 NOT NULL,

  -- Metadata
  purchase_date date,
  notes text,
  portfolio_name text, -- Group assets into portfolios

  -- Cached calculations (for performance)
  total_cost numeric GENERATED ALWAYS AS (quantity * avg_buy_price) STORED,
  current_value numeric GENERATED ALWAYS AS (quantity * current_price) STORED,
  unrealized_gain numeric GENERATED ALWAYS AS ((quantity * current_price) - (quantity * avg_buy_price)) STORED,

  -- Timestamps
  last_price_update timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,

  UNIQUE(user_id, symbol, type)
);

CREATE INDEX idx_assets_user_type ON public.assets(user_id, type);
CREATE INDEX idx_assets_portfolio ON public.assets(user_id, portfolio_name);

-- ============================================================================
-- 13. ASSET TRANSACTIONS (Buy/Sell history)
-- Purpose: Complete transaction history for each asset
-- ============================================================================
CREATE TABLE public.asset_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  asset_id bigint REFERENCES public.assets ON DELETE CASCADE NOT NULL,

  transaction_type text NOT NULL CHECK (transaction_type IN ('buy', 'sell', 'dividend', 'split', 'bonus')),
  quantity numeric NOT NULL,
  price_per_unit numeric NOT NULL CHECK (price_per_unit >= 0),
  total_amount numeric GENERATED ALWAYS AS (quantity * price_per_unit) STORED,
  fees numeric DEFAULT 0,

  transaction_date date NOT NULL,
  notes text,

  created_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX idx_asset_transactions_asset ON public.asset_transactions(asset_id, transaction_date DESC);
CREATE INDEX idx_asset_transactions_user_date ON public.asset_transactions(user_id, transaction_date DESC);

-- ============================================================================
-- 14. TASKS
-- Purpose: Financial and general task management
-- ============================================================================
CREATE TABLE public.task_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  name text NOT NULL,
  icon text,
  color text,
  created_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE(user_id, name)
);

CREATE TABLE public.tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  title text NOT NULL,
  category text, -- Free text for flexibility
  priority task_priority DEFAULT 'medium' NOT NULL,
  status task_status DEFAULT 'todo' NOT NULL,
  deadline date,
  notes text,
  completed_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX idx_tasks_user_status ON public.tasks(user_id, status);
CREATE INDEX idx_tasks_deadline ON public.tasks(user_id, deadline) WHERE status = 'todo';

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) - Apply to all tables
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaction_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.debts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaction_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaction_tag_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budget_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recurring_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asset_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- Create policies (simple pattern for all tables)
DO $$
DECLARE
    table_name text;
BEGIN
    FOR table_name IN
        SELECT tablename FROM pg_tables
        WHERE schemaname = 'public'
        AND tablename IN (
            'categories', 'transaction_items', 'wallets', 'projects', 'debts',
            'transactions', 'transaction_tags', 'budgets', 'budget_alerts',
            'recurring_transactions', 'financial_goals', 'assets',
            'asset_transactions', 'task_categories', 'tasks'
        )
    LOOP
        EXECUTE format('
            CREATE POLICY "Users can manage own data" ON public.%I
            FOR ALL USING (auth.uid() = user_id)
        ', table_name);
    END LOOP;
END $$;

-- Special policy for junction table
CREATE POLICY "Users can manage own tag assignments"
ON public.transaction_tag_assignments FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.transactions
    WHERE transactions.id = transaction_tag_assignments.transaction_id
    AND transactions.user_id = auth.uid()
  )
);

-- ============================================================================
-- VIEWS - Optimized for common queries
-- ============================================================================

-- Wallet balances with real-time calculation
CREATE VIEW public.wallet_balances_view AS
SELECT
  w.id,
  w.user_id,
  w.name,
  w.type,
  w.initial_balance,
  w.currency,
  w.is_active,
  w.is_excluded_from_total,
  COALESCE(income.total, 0) AS total_income,
  COALESCE(expense.total, 0) AS total_expense,
  COALESCE(transfer_in.total, 0) AS total_transfer_in,
  COALESCE(transfer_out.total, 0) AS total_transfer_out,
  w.initial_balance +
    COALESCE(income.total, 0) -
    COALESCE(expense.total, 0) +
    COALESCE(transfer_in.total, 0) -
    COALESCE(transfer_out.total, 0) AS current_balance
FROM public.wallets w
LEFT JOIN (
  SELECT wallet_id, SUM(amount) AS total
  FROM public.transactions
  WHERE type = 'income'
  GROUP BY wallet_id
) income ON income.wallet_id = w.id
LEFT JOIN (
  SELECT wallet_id, SUM(amount) AS total
  FROM public.transactions
  WHERE type = 'expense'
  GROUP BY wallet_id
) expense ON expense.wallet_id = w.id
LEFT JOIN (
  SELECT to_wallet_id, SUM(amount) AS total
  FROM public.transactions
  WHERE type = 'transfer'
  GROUP BY to_wallet_id
) transfer_in ON transfer_in.to_wallet_id = w.id
LEFT JOIN (
  SELECT wallet_id, SUM(amount) AS total
  FROM public.transactions
  WHERE type = 'transfer'
  GROUP BY wallet_id
) transfer_out ON transfer_out.wallet_id = w.id;

-- Project spending summary
CREATE VIEW public.project_summary_view AS
SELECT
  p.id,
  p.user_id,
  p.name,
  p.description,
  p.total_budget,
  p.status,
  p.deadline,
  COALESCE(SUM(t.amount), 0) AS actual_spent,
  p.total_budget - COALESCE(SUM(t.amount), 0) AS remaining_budget,
  CASE
    WHEN p.total_budget > 0 THEN ROUND((COALESCE(SUM(t.amount), 0) / p.total_budget * 100)::numeric, 2)
    ELSE 0
  END AS budget_percentage_used,
  COUNT(t.id) AS transaction_count,
  MAX(t.date) AS last_transaction_date
FROM public.projects p
LEFT JOIN public.transactions t ON t.project_id = p.id AND t.type = 'expense'
GROUP BY p.id;

-- Monthly budget tracking
CREATE VIEW public.budget_tracking_view AS
SELECT
  b.id,
  b.user_id,
  b.month,
  b.year,
  c.name AS category_name,
  c.type AS category_type,
  b.amount AS budget_amount,
  COALESCE(SUM(t.amount), 0) AS spent_amount,
  b.amount - COALESCE(SUM(t.amount), 0) AS remaining_amount,
  CASE
    WHEN b.amount > 0 THEN ROUND((COALESCE(SUM(t.amount), 0) / b.amount * 100)::numeric, 2)
    ELSE 0
  END AS percentage_used,
  CASE
    WHEN COALESCE(SUM(t.amount), 0) > b.amount THEN true
    ELSE false
  END AS is_exceeded
FROM public.budgets b
LEFT JOIN public.categories c ON c.id = b.category_id
LEFT JOIN public.transactions t ON
  t.item_id IN (
    SELECT id FROM public.transaction_items WHERE category_id = b.category_id
  )
  AND EXTRACT(MONTH FROM t.date) = b.month
  AND EXTRACT(YEAR FROM t.date) = b.year
  AND t.type = 'expense'
GROUP BY b.id, b.user_id, b.month, b.year, c.name, c.type, b.amount;

-- Net worth calculation
CREATE VIEW public.net_worth_view AS
SELECT
  user_id,
  SUM(current_balance) FILTER (WHERE is_excluded_from_total = false) AS total_liquid_assets,
  SUM(current_balance) FILTER (WHERE is_excluded_from_total = true) AS total_liabilities,
  SUM(current_balance) FILTER (WHERE is_excluded_from_total = false) -
    SUM(current_balance) FILTER (WHERE is_excluded_from_total = true) AS net_worth
FROM public.wallet_balances_view
GROUP BY user_id;

-- Investment portfolio summary
CREATE VIEW public.portfolio_summary_view AS
SELECT
  user_id,
  portfolio_name,
  type,
  COUNT(*) AS asset_count,
  SUM(total_cost) AS total_invested,
  SUM(current_value) AS current_value,
  SUM(unrealized_gain) AS total_unrealized_gain,
  CASE
    WHEN SUM(total_cost) > 0 THEN ROUND((SUM(unrealized_gain) / SUM(total_cost) * 100)::numeric, 2)
    ELSE 0
  END AS return_percentage
FROM public.assets
GROUP BY user_id, portfolio_name, type;

-- ============================================================================
-- FUNCTIONS - Automation & Business Logic
-- ============================================================================

-- Function to update wallet balance (cached)
CREATE OR REPLACE FUNCTION update_wallet_balance()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
    -- Update source wallet
    IF NEW.wallet_id IS NOT NULL THEN
      UPDATE public.wallets
      SET current_balance = (
        SELECT current_balance FROM public.wallet_balances_view WHERE id = NEW.wallet_id
      ),
      updated_at = now()
      WHERE id = NEW.wallet_id;
    END IF;

    -- Update destination wallet (for transfers)
    IF NEW.to_wallet_id IS NOT NULL THEN
      UPDATE public.wallets
      SET current_balance = (
        SELECT current_balance FROM public.wallet_balances_view WHERE id = NEW.to_wallet_id
      ),
      updated_at = now()
      WHERE id = NEW.to_wallet_id;
    END IF;
  END IF;

  IF TG_OP = 'DELETE' THEN
    IF OLD.wallet_id IS NOT NULL THEN
      UPDATE public.wallets
      SET current_balance = (
        SELECT current_balance FROM public.wallet_balances_view WHERE id = OLD.wallet_id
      ),
      updated_at = now()
      WHERE id = OLD.wallet_id;
    END IF;

    IF OLD.to_wallet_id IS NOT NULL THEN
      UPDATE public.wallets
      SET current_balance = (
        SELECT current_balance FROM public.wallet_balances_view WHERE id = OLD.to_wallet_id
      ),
      updated_at = now()
      WHERE id = OLD.to_wallet_id;
    END IF;
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_wallet_balance
AFTER INSERT OR UPDATE OR DELETE ON public.transactions
FOR EACH ROW EXECUTE FUNCTION update_wallet_balance();

-- Function to update project spent amount
CREATE OR REPLACE FUNCTION update_project_spent()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
    IF NEW.project_id IS NOT NULL AND NEW.type = 'expense' THEN
      UPDATE public.projects
      SET spent_amount = (
        SELECT COALESCE(SUM(amount), 0)
        FROM public.transactions
        WHERE project_id = NEW.project_id AND type = 'expense'
      ),
      updated_at = now()
      WHERE id = NEW.project_id;
    END IF;
  END IF;

  IF TG_OP = 'DELETE' THEN
    IF OLD.project_id IS NOT NULL AND OLD.type = 'expense' THEN
      UPDATE public.projects
      SET spent_amount = (
        SELECT COALESCE(SUM(amount), 0)
        FROM public.transactions
        WHERE project_id = OLD.project_id AND type = 'expense'
      ),
      updated_at = now()
      WHERE id = OLD.project_id;
    END IF;
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_project_spent
AFTER INSERT OR UPDATE OR DELETE ON public.transactions
FOR EACH ROW EXECUTE FUNCTION update_project_spent();

-- Function to update debt remaining amount
CREATE OR REPLACE FUNCTION update_debt_payment()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
    IF NEW.debt_id IS NOT NULL AND NEW.type = 'expense' THEN
      UPDATE public.debts
      SET remaining_amount = remaining_amount - NEW.amount,
          is_paid = CASE WHEN (remaining_amount - NEW.amount) <= 0 THEN true ELSE false END,
          updated_at = now()
      WHERE id = NEW.debt_id;
    END IF;
  END IF;

  IF TG_OP = 'DELETE' THEN
    IF OLD.debt_id IS NOT NULL AND OLD.type = 'expense' THEN
      UPDATE public.debts
      SET remaining_amount = remaining_amount + OLD.amount,
          is_paid = false,
          updated_at = now()
      WHERE id = OLD.debt_id;
    END IF;
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_debt_payment
AFTER INSERT OR UPDATE OR DELETE ON public.transactions
FOR EACH ROW EXECUTE FUNCTION update_debt_payment();

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to all tables with updated_at
CREATE TRIGGER trigger_update_categories_timestamp BEFORE UPDATE ON public.categories FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trigger_update_transaction_items_timestamp BEFORE UPDATE ON public.transaction_items FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trigger_update_wallets_timestamp BEFORE UPDATE ON public.wallets FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trigger_update_projects_timestamp BEFORE UPDATE ON public.projects FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trigger_update_debts_timestamp BEFORE UPDATE ON public.debts FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trigger_update_transactions_timestamp BEFORE UPDATE ON public.transactions FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trigger_update_budgets_timestamp BEFORE UPDATE ON public.budgets FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trigger_update_recurring_timestamp BEFORE UPDATE ON public.recurring_transactions FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trigger_update_goals_timestamp BEFORE UPDATE ON public.financial_goals FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trigger_update_assets_timestamp BEFORE UPDATE ON public.assets FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trigger_update_tasks_timestamp BEFORE UPDATE ON public.tasks FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================================
-- COMPLETE! Schema V2 ready for production
-- ============================================================================
